name: Deploy Function App

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.100'

    - name: 'Build'
      shell: pwsh
      run: |
        pushd .
        dotnet build --configuration Release --output ./output
        popd

    - name: 'Publish Azure Function'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: alejof-netlify
        package: './output'
        publish-profile: ${{ secrets.PUBLISH_PROFILE }}

# For more information on GitHub Actions:
#   https://help.github.com/en/categories/automating-your-workflow-with-github-actions

# Template from
#   https://github.com/Azure/actions-workflow-samples/blob/master/windows-dotnet-functionapp-on-azure.yml
